# Created by trellis-cli v0.7.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  sunderstormstage.christopherdias.com:
    site_hosts:
    - canonical: test.sunderstorm.com
      redirects: []
    local_path: ../site
    branch: main
    repo: git@github.com:cjknight11/sunderstorm.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
